[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rusnap = "0.1.0"

[build-dependencies]
rusnap-build = "0.1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
